# Generated by Django 3.0.2 on 2021-04-15 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tourismm', '0002_ttd'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ttd',
        ),
    ]
