# Generated by Django 3.0.2 on 2021-04-16 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourismm', '0004_ttd'),
    ]

    operations = [
        migrations.AddField(
            model_name='discover',
            name='activities',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='discover',
            name='cost',
            field=models.TextField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ttd',
            name='activities',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='ttd',
            name='cost',
            field=models.TextField(max_length=50, null=True),
        ),
    ]
