# Generated by Django 3.0.2 on 2021-04-17 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourismm', '0005_auto_20210416_1220'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, null=True)),
                ('desiredplace', models.CharField(max_length=250, null=True)),
                ('noofpep', models.CharField(max_length=100, null=True)),
                ('checkindate', models.DateField(max_length=100, null=True)),
                ('email', models.EmailField(max_length=100, null=True)),
                ('number', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
