# Generated by Django 3.0.2 on 2021-04-17 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourismm', '0009_gallery_gallery2_gallery3'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Gallery2',
        ),
        migrations.DeleteModel(
            name='Gallery3',
        ),
        migrations.RenameField(
            model_name='gallery',
            old_name='image',
            new_name='first_image',
        ),
        migrations.AddField(
            model_name='gallery',
            name='second_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='gallery',
            name='third_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
