# Generated by Django 3.0.2 on 2021-04-17 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourismm', '0011_auto_20210417_2318'),
    ]

    operations = [
        migrations.AddField(
            model_name='ttd',
            name='first_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='ttd',
            name='second_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='ttd',
            name='third_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
