# Generated by Django 3.0.2 on 2021-04-19 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourismm', '0012_auto_20210417_2353'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Gallery',
        ),
        migrations.RemoveField(
            model_name='book',
            name='desiredplace',
        ),
        migrations.AddField(
            model_name='book',
            name='Package',
            field=models.CharField(choices=[('Family Package', 'Family Package'), ('Solo Package', 'Solo Package'), ('Complete Guided Package', 'Complete Guided Package')], default='pokhara', max_length=100),
        ),
    ]
