# Generated by Django 3.0.2 on 2021-04-19 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tourismm', '0013_auto_20210419_2055'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='noofpep',
            new_name='No_Of_People',
        ),
    ]
