# Generated by Django 3.0.2 on 2021-04-19 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourismm', '0016_auto_20210419_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='Package',
            field=models.CharField(choices=[('HeavenView Hotel', 'HeavenView Hotel'), ('NepStay', 'NepStay')], default='Family Package', max_length=100),
        ),
        migrations.AlterField(
            model_name='flightbook',
            name='Airlines',
            field=models.CharField(choices=[('Buddha Airlines', 'Buddha Airlines')], default='Buddha Airlines', max_length=100),
        ),
        migrations.AlterField(
            model_name='hotelbook',
            name='Hotel',
            field=models.CharField(choices=[('Buddha Airlines', 'Buddha Airlines')], default='NepStay', max_length=100),
        ),
    ]
