# Generated by Django 3.0.2 on 2021-04-19 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tourismm', '0018_auto_20210419_2146'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FlightBook',
            new_name='Flight',
        ),
        migrations.RenameModel(
            old_name='HotelBook',
            new_name='Hotel',
        ),
    ]
