# Generated by Django 3.0.2 on 2021-04-19 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tourismm', '0019_auto_20210419_2252'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='Check_In_Date',
            new_name='check_In_Date',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='Email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='No_Of_People',
            new_name='no_Of_People',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='Number',
            new_name='number',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='Package',
            new_name='package',
        ),
        migrations.RenameField(
            model_name='flight',
            old_name='Airlines',
            new_name='airlines',
        ),
        migrations.RenameField(
            model_name='flight',
            old_name='Check_In_Date',
            new_name='check_In_Date',
        ),
        migrations.RenameField(
            model_name='flight',
            old_name='Email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='flight',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='flight',
            old_name='No_Of_People',
            new_name='no_Of_People',
        ),
        migrations.RenameField(
            model_name='flight',
            old_name='Number',
            new_name='number',
        ),
        migrations.RenameField(
            model_name='hotel',
            old_name='Check_In_Date',
            new_name='check_In_Date',
        ),
        migrations.RenameField(
            model_name='hotel',
            old_name='Email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='hotel',
            old_name='Hotel',
            new_name='hotel',
        ),
        migrations.RenameField(
            model_name='hotel',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='hotel',
            old_name='No_Of_People',
            new_name='no_Of_People',
        ),
        migrations.RenameField(
            model_name='hotel',
            old_name='Number',
            new_name='number',
        ),
    ]
